# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Block chain application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Execute SCA - ❄️ flake8
      run: |
        flake8 --ignore E501,W503,F841,E722 --exclude .tox,*.egg,build,__pycache__,htmlcov
    - name:  Execute SCA - 💖 mypy
      run: |
        mypy src tests
    - name:  Execute SCA - 🧹 pylint
      run: |
        pylint src tests --disable=C0301,R0801,R0902,W0640,R0914,W0702,R1732,W0604
    - name:  Execute SCA - 🦅 vulture
      run: |
        vulture src tests
    - name:  Execute Unit test - 🧪 Pytest
      run : |
        pytest

    - name: Upload Code Coverage as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Coverage Artifact
        path: htmlcov/
        
  
  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -e .

  #   - name: Generate documentation 📚
  #     run: |
  #       tracker-doc

  #   - name: Upload documentation as artifact
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: documentation
  #       path: docs/

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Generate Build ⚙️
      run: |
        python -m build

    - name: Upload Distribution as artifact
      uses: actions/upload-artifact@v3
      with:
        name: Distribution
        path: dist/
    
        
